
-- utils usage as of 2020-10-16:
--     u.any
--     u.cb
--     u.copy
--     u.each
--     u.equal
--     u.extend
--     u.filter
--     u.flatten
--     u.getfield
--     u.greaterThan
--     u.groupBy
--     u.identity
--     u.keys
--     u.length
--     u.levenshteinDistance
--     u.map
--     u.partial
--     u.roundToNearest
--     u.setfield
--     u.toBool
--     u.values
--     u.zip
